services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

  backend:
    build: ./server
    ports:
      - "5000:5000"
